### ISSUE TITLE
Post 1,2, paquete!

### ISSUE THREAD

**Issue by yabellini** [pablotis/estacion-r.github.io#8]
Hola! Algunos comentarios y consideraciones generales.  Puedes tomarlas/ignorarlas.

### Primero
* Me parece un post fundamental y especialmente en español, como para iniciar.  Gracias por armarlo.

### Comentario de curiosa nomás: 
* Me gusta la anlogía con los postrecitos, tengo mas de 30 y no los conocía.  Me pregunto también si es algo específico de un país? (de ser así lo pondría entre parentesis en el texto (si tenes mas de 30 años (y sos de Argentina / sos del Sur de América)....o algo por el estilo.
(Re nota al pie: ahora hay una cosa que se llama torta en taza que es muy similar: mezcla de la bolsita. leche en una taza, microonda y tenes una torta rica, lista para comer con una cuchara) :-P 

## Eras

* Me encanta este caminito de evolución en el desarrollo en R de una persona!!  Creo muchismos nos identificamos con estas etapas.

* No creo que RMarkdown petenece a la era del script, para mi las notebooks son una evolución del script y pueden generar automatizaciones y acomodar flujos de trabajos de publicaciones de forma muy prolija.  Son otra forma de programar y son útiles al proposito del reporte y del mix prosa - codigo - resultado.  Pero entiendo si por cuestión de espacio/simplificación las pones juntas.  Creo que lo que me hace mas ruido es lo de la automatizacion rudimentaria si hablamos de rmarkdowns.

## Bib
* Buenismo que presentes de una la bib de referencia.  

* Creo que este texto "Ambos autores tienen una inclinación por poner el foco en la accesibilidad a la hora de transmitir conocimiento, cosa para nada despreciable en el mundo de la programación." lo pondría como una nota al pie.  Estoy de acuerdo con tu apreciación pero no está relacionado con el metié del artículo.

## Manos a la obra

* Cuando arrancás no explicas donde debemos hacer esto.  ¿Es en RStudio o nuestra IDE favorita?, ¿Es en la consola de R?, ¿Es en un script?, ¿¡dónde, donde escribo todo esto!? :-P 

* Cuando mencionar que se crea el proyecto podes decir que si lo hacen en RStudio se abre una nueva instancia con ese proyecto y que desde allí vamos a trabajar en ese espacio.

* El "En pocas palabras" no se muestra desplegado (entiendo que esa es la idea) y yo no me esperaba ese contenido allí.  Capaz que agregarle "En pocas palabras: el esqueleto de un proyecto de paquete" o algo por el estilo.  

* Los gift están buenisimos, me parece que con fondo blanco se vería mejor.  A mi me cuesta ver lo que pasa (capaz una mezcla de "Yani necesitas anteojos" y pantalla no tan grande) 

### Paso 5

* El texto: "Y esto es porque una de las razones por las cuales hacer un paquete es la posibilidad de documentar, actividad cuya popularidad es inversamente proporcional a la importancia que tiene."  Debería ser algo como "Y esta es una de las razones por las cuales es buena idea hacer un paquete, la posibilidad de documentar; actividad cuya popularidad es inversamente proporcional a la importancia que tiene." ?

### Final
* Agregar Alguna referencia a reolución de problemas si resulta que no sale el 0 0 0 (errors, warning, notes).  Puede ser link al libro.

* Buenisimas las otras menciones sobre como seguir.  Capaz da para un segundo blog post de la serie?

**Comment by pablotis** [comment]
Muchas gracias @yabellini! Todas las observaciones súper atinadas, la estoy implementando. 

Aprovecho para contestar algunos de los comentarios, por cómo lo veo.

## Ejemplo de Intro

Qué desafío pensarse siendo leído por fuera de los límites geográficos de uno! (tengo que googlear la torta de taza)

## Eras

Efectivamente, no creo que Rmarkdown pertenezca a la misma era que un R script. De hecho es algo que comento en los cursos que dicto! Creo que lo incluí porque, justamente, es común encontrar cursos de intro a R donde se comienza con Rmarkdown como primer plataforma de escritura.

## Manos a la obra

Los "En pocas palabras" son un experimento que efectivamente necesitan más sintonía fina. La idea es que no es necesario leerlos, peor en caso de querer profundizar estén allí, disponibles. Es verdad que al ofrecerlo, seguramente se lea, pero creo que me gustaría recibir más devoluciones al respecto y ver cómo se responde a esa sección. Voy a probar con un mejor ícono, algo que simule el "click" para incentivar verlo al menos.

Coincido con el color de los giffs! Pero será algo a mejorar en un próximo posteo, por tiempos y vagancia principalmente.

## Final

Con aportes como los tuyos hay segundo posteo, eso seguro!
